GET http://localhost:{{$dotenv PORT}}/{{$dotenv BASE_URL}}/restaurants
Content-Type: application/json

### CREATE A NEW RESTAURANT
POST http://localhost:{{$dotenv PORT}}/{{$dotenv BASE_URL}}/restaurants
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
  "name": "Sam Loco Ent.",
  "phone": "+233542433262",
  "address": "Adenta, Asylum Down"
}

### UPDATE A RESTAURANT DETAILS EITHER -> ONLY USER WHO CREATED RECORD OR SYSTEM ADMIN CAN PERFORM THIS OPERATION
PATCH http://localhost:{{$dotenv PORT}}/{{$dotenv BASE_URL}}/restaurants/2
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
  "name": "WATER REED",
  "phone": "+233542433262",
  "address": "Adenta, Asylum Down"
}


### DELETE A RESTAURANT BY ID -> ONLY USER WHO CREATED RECORD OR SYSTEM ADMIN CAN PERFORM THIS OPERATION
DELETE http://localhost:{{$dotenv PORT}}/{{$dotenv BASE_URL}}/restaurants/10
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}