POST http://localhost:{{$dotenv PORT}}/{{$dotenv BASE_URL}}/users
Content-Type: application/json

{
    "firstName": "Daniel",
    "lastName": "Narh",
    "email": "naphthanewman234@gmail.com",
    "phone": "+233542437269",
    "password": "12345678",
    "confirmPassword": "12345678",
    "address": "Lake Bosomtwe Junction"

}

###
POST http://localhost:{{$dotenv PORT}}/{{$dotenv BASE_URL}}/users/login
Content-Type: application/json

{
    "email": "naphthanewman@gmail.com",
    "password": "12345678"
}


###
GET http://localhost:{{$dotenv PORT}}/{{$dotenv BASE_URL}}/users/logout
Content-Type: application/json